### ISSUE TITLE
Feat: setup backend

### ISSUE THREAD

**Issue by manamana32321** [skku-amang/Homepage-FrontEnd#1]
~~
빠르고 간단하게 백엔드를 추가하려고 합니다.
따라서 Firebase를 채택합니다.
~~
백엔드 인력이 추가됨에 따라 NestJS로 변경합니다.
이유는 다음과 같습니다.
1. 어느 정도 복잡성이 있는 백엔드 처리력이 필요함
2. 프론트엔드는 현재 Typescript + NextJS 조합으로 가는 상황이라 추후 백엔드 지원도 가능하게 됨

**Comment by manamana32321** [comment]
Django로 갑니다...

**Comment by Webishappiness** [comment]
ㅋㅋㅋㅋㅋㅋ
