### ISSUE TITLE
점심 메뉴를 정해주세요

### ISSUE THREAD

**Issue by EddieDawn** [skku-amang/Homepage-FrontEnd#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

짜장면 vs 짬뽕

**Comment by manamana32321** [comment]
세상에서 가장 어려운 질문을 던지다니 너무하시군요
Close 하겠습니다...

**Comment by Webishappiness** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
